## Coding Challenge 10a: Interactive charts

In this notebook, I use Harvard Atlas ECI to map the Economic Complexity of countries

Link to data:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/XTAQMC

In [ ]:
%pip install altair   # Some packages need to be installed to the virtual machine before we can import them into our notebook. We can do this with '!pip install'

Note: you may need to restart the kernel to use updated packages.

ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np
import altair as alt

from json import loads, dumps

## 1) Interactive map of complexity rankings

### Importing data

In [3]:
eci = pd.read_stata("../data/rankings.dta") # ECI Rankings
country_code = pd.read_csv('../data/location_country.csv') # Country codes

In [6]:
eci.head()

,country_id,year,sitc_eci,hs_eci,growth_proj,sitc_eci_rank,hs_eci_rank
2885,4,2000,-0.315885,-0.155740,NaN,78,72
2886,8,2000,-0.125142,-0.196624,NaN,71,75
2887,12,2000,-0.985822,-1.039474,NaN,123,126
2888,24,2000,-1.909197,-2.031919,NaN,141,142
2889,31,2000,-0.367642,-0.133683,NaN,81,71

In [15]:
country_code.head()

   country_id name_short_en iso3_code  legacy_location_id
0         533         Aruba       ABW                   0
1           4   Afghanistan       AFG                   1
2          24        Angola       AGO                   2
3         660      Anguilla       AIA                   3
4           8       Albania       ALB                   4

### Cleaning

In [4]:
# Only data from 2000's
eci = eci[eci['year']>=2000]

# Merge with country code
eci_country_code = pd.merge(eci, country_code, on="country_id")

# Keeping key columns
eci_country_code = eci_country_code[['year','name_short_en', 'iso3_code','hs_eci_rank']]

eci_country_code

# Renaming columns
eci_country_code.rename(columns={

    "name_short_en" : "country",
    "iso3_code": "ISO3"

}, inplace=True)

eci_country_code

      year      country ISO3  hs_eci_rank
0     2000  Afghanistan  AFG           72
1     2000      Albania  ALB           75
2     2000      Algeria  DZA          126
3     2000       Angola  AGO          142
4     2000   Azerbaijan  AZE           71
...    ...          ...  ...          ...
3330  2022      Uruguay  URY           59
3331  2022   Uzbekistan  UZB           71
3332  2022    Venezuela  VEN          109
3333  2022        Yemen  YEM          125
3334  2022       Zambia  ZMB           99

[3335 rows x 4 columns]

### Exporting as CSV

In [6]:
eci_country_code.to_csv('../data/map_data.csv', index=False)

### Plotting

I do not have to plot since I already have the JSON plot from the course seminar

## 2) Interactive chart of product space and countries

### Importing data

### Cleaning data

### Exporting as CSV